#!/usr/bin/env python3

import sys
import re

import llfuse

from canvas import Canvas, format_json
from cached_class import CachedClass
from vfs import VFS, std_dir, std_file


class CanvasFS(VFS):
    def __init__(self, canvas):
        super(CanvasFS, self).__init__()

        self.canvas = canvas

    def get_contents(self, path):
        routes = [
            ('', self.root),
            ('courses', self.courses),
            ('courses/:id', self.course),
            ('courses/:id/all.json', self.course_info),
            ('courses/:id/name', self.course_name),
        ]

        for route, fun in routes:
            regex = '^' + re.sub(':([^/]+)', r'(?P<\1>[^/]+)', route) + '$'
            m = re.match(regex, path)
            if m is not None:
                return fun(**m.groupdict())

    def root(self):
        return std_dir(['courses'])

    def courses(self):
        course_ids = [str(course['id']) for course
                      in self.canvas.courses()]
        return std_dir(course_ids)

    def course(self, id):
        return std_dir(['all.json', 'name'])

    def course_info(self, id):
        course = self.canvas.course(id)
        data = format_json(course).encode('utf-8')
        return std_file(data)

    def course_name(self, id):
        course = self.canvas.course(id)
        data = course['name'].encode('utf-8') + b'\n'
        return std_file(data)

def main(args):
    try:
        [mountpoint] = args
    except ValueError:
        print('error: wrong arguments', file=sys.stderr)
        print('usage: fuse MOUNTPOINT',
              file=sys.stderr)
        return 1

    fs = CanvasFS(CachedClass(Canvas()))
    fuse_options = set(llfuse.default_options)
    fuse_options.add('fsname=canvasfs')
    # fuse_options.add('debug')
    llfuse.init(fs, mountpoint, fuse_options)

    try:
        llfuse.main(workers=1)
    except:
        llfuse.close(unmount=False)
        raise

    llfuse.close()
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
