#!/usr/bin/env python3

import sys
import re
import errno
import urllib.request

import llfuse

from canvas import Canvas, format_json
from cached_class import CachedClass
from vfs import VFS, std_dir, std_file


class CanvasFS(VFS):
    def __init__(self, canvas):
        super(CanvasFS, self).__init__()

        self.canvas = canvas

        self.route_taken = None

        self.routes = [
            ('', self.root),

            ('self', self.self_),
            ('self/files', self.self_files),
            ('self/files/:file', self.self_file),

            ('courses', self.courses),
            ('courses/:course_id', self.course),
            ('courses/:course_id/all.json', self.course_info),
            ('courses/:course_id/name', self.course_name),
            ('courses/:course_id/calendar.ics', self.course_calendar),
            ('courses/:course_id/students', self.course_students),
            ('courses/:course_id/students/:user_id', self.course_student),
            ('courses/:course_id/students/:user_id/name', self.course_student_name),
            ('courses/:course_id/students/:user_id/login_id', self.course_student_login_id),
        ]

    def get_contents(self, path):
        for route, fun in self.routes:
            regex = '^' + re.sub(':([^/]+)', r'(?P<\1>[^/]+)', route) + '$'
            m = re.match(regex, path)
            if m is not None:
                self.route_taken = route # used by `CanvasFS.static_elements`.
                return fun(**m.groupdict())

    def static_elements(self):
        elements = []
        start = self.route_taken
        if start:
            start += '/'
        for route, fun in self.routes:
            if route.startswith(start):
                rest = route[len(start):]
                if rest and not rest.startswith(':') and not '/' in rest:
                    elements.append(rest)
        return elements

    def root(self):
        return std_dir(self.static_elements())

    def self_(self):
        return std_dir(self.static_elements())

    def self_files(self):
        # TODO: Timestamps.
        files = self.canvas.get('users/self/files')
        return std_dir([file['display_name'] for file in files])

    def self_file(self, file):
        files = self.canvas.get('users/self/files', search_term=file)
        assert len(files) == 1
        url = files[0]['url']
        with urllib.request.urlopen(url) as f:
            data = f.read()
        return std_file(data)
    
    def courses(self):
        course_ids = [str(course['id']) for course
                      in self.canvas.courses()]
        return std_dir(course_ids)

    def course(self, course_id):
        return std_dir(self.static_elements())

    def course_info(self, course_id):
        course = self.canvas.course(course_id)
        data = format_json(course)
        return std_file(data)

    def course_name(self, course_id):
        course = self.canvas.course(course_id)
        data = course['name'] + '\n'
        return std_file(data)

    def course_calendar(self, course_id):
        course = self.canvas.course(course_id)
        url = course['calendar']['ics']
        with urllib.request.urlopen(url) as f:
            data = f.read()
        return std_file(data)

    def course_students(self, course_id):
        student_ids = [str(student['id']) for student
                       in self.canvas.all_students(course_id)]
        return std_dir(student_ids)

    def course_student(self, course_id, user_id):
        elements = self.static_elements()
        student = self.canvas.course_student(course_id, user_id)
        if 'login_id' not in student:
            elements.remove('login_id')
        return std_dir(elements)

    def course_student_name(self, course_id, user_id):
        student = self.canvas.course_student(course_id, user_id)
        data = student['name'] + '\n'
        return std_file(data)

    def course_student_login_id(self, course_id, user_id):
        student = self.canvas.course_student(course_id, user_id)
        try:
            data = student['login_id'] + '\n'
        except KeyError: # Permission denied (not a TA)
            raise llfuse.FUSEError(errno.EACCES)
        return std_file(data)

def main(args):
    try:
        [mountpoint] = args
    except ValueError:
        print('error: wrong arguments', file=sys.stderr)
        print('usage: fuse MOUNTPOINT',
              file=sys.stderr)
        return 1

    debug = False

    fs = CanvasFS(CachedClass(Canvas()))
    fuse_options = set(llfuse.default_options)
    fuse_options.add('fsname=canvasfs')
    if debug:
        fuse_options.add('debug')
    llfuse.init(fs, mountpoint, fuse_options)

    try:
        llfuse.main(workers=1)
    except:
        llfuse.close(unmount=False)
        raise

    llfuse.close()
    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
