#!/usr/bin/env python3

import sys
import re

from canvas import *


def main(args):
    # Well...
    if len(args) > 1 and args[0] == 'ABORT':
        abort = True
        args = args[1:]
    else:
        abort = False

    try:
        [course_id, ass_group_name, group_file] = args
    except ValueError:
        print('error: wrong arguments', file=sys.stderr)
        print('usage: group_students COURSE_ID ASSIGNMENT_GROUP_NAME GROUP_FILE',
              file=sys.stderr)
        return 1
    
    with open(group_file) as f:
        groups = [line.split(' ') for line in f.read().strip().split('\n')]

    c = Canvas()
    group_cats = c.group_categories(course_id)
    group_cat = next(filter(lambda c: c['name'] == ass_group_name,
                            group_cats))
    group_cat_id = group_cat['id']

    if abort:
        c.delete_all_assignment_groups(group_cat_id)
        return 0
    
    students = c.all_students(course_id)

    # Mapping from abc123 (or whatever is before @ in the KU email address) to
    # user id.
    user_ids = {}
    for s in students:
        m = re.match('^(.+?)@', s['login_id'])
        user_ids[m.group(1)] = s['id']

    for users, i in zip(groups, range(0, len(groups))):
        name = '{} {:03d}'.format(ass_group_name, i)
        users = list(map(lambda abc123: user_ids[abc123], users))
        group = c.create_group(group_cat_id, name)
        group_id = group['id']
        c.add_group_members(group_id, users)

    return 0

if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
